export default {
  LOAD_DRIVER_STANDINGS: 'LOAD_DRIVER_STANDINGS',
  LOAD_RACES: 'LOAD_RACES',
  LOAD_CONSTRUCTOR_STANDINGS: 'LOAD_CONSTRUCTOR_STANDINGS',
  ADD_CHART_DRIVER: 'ADD_CHART_DRIVER',
  DELETE_CHART_DRIVER: 'DELETE_CHART_DRIVER',
  LOAD_CHART_POINTS: 'LOAD_CHART_POINTS'
};
