export default {
  LOAD_SUGGESTED_ARTISTS: 'LOAD_SUGGESTED_ARTISTS',
  LOAD_FAVOURITE_ARTISTS: 'LOAD_FAVOURITE_ARTISTS',
  DELETE_FAVOURITE_ARTISTS: 'DELETE_FAVOURITE_ARTISTS',
  ADD_FAVOURITE_ARTISTS: 'ADD_FAVOURITE_ARTISTS',
  LOAD_SEARCHED_ARTISTS: 'LOAD_SEARCHED_ARTISTS',
  LOAD_ARTIST_DETAILS: 'LOAD_ARTIST_DETAILS'
};
