export default {
  LOAD_GNOMES: 'LOAD_GNOMES',
  LOAD_CURRENT_GNOME: 'LOAD_CURRENT_GNOME',
  ADD_FRIEND: 'ADD_FRIEND',
  REMOVE_FRIEND: 'REMOVE_FRIEND',
  ADD_ADVERSARY: 'ADD_ADVERSARY',
  REMOVE_ADVERSARY: 'REMOVE_ADVERSARY'
};
