export default {
  LOAD_PRODUCT_LIST: 'LOAD_PRODUCT_LIST',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  REMOVE_ALL_FROM_CART: 'REMOVE_ALL_FROM_CART',
  UPDATE_PRODUCT_AMOUNT: 'UPDATE_PRODUCT_AMOUNT',
};
