export default {
  LOAD_DASHBOARD: 'LOAD_DASHBOARD',
  LOAD_DETAILS: 'LOAD_DETAILS',
  LOAD_INFORMATION: 'LOAD_INFORMATION',
  LOAD_FAVORITES: 'LOAD_FAVORITES',
  ADD_FAVORITES: 'ADD_FAVORITES',
  DELETE_FAVORITES: 'DELETE_FAVORITES',
  UPDATE_FAVORITE: 'UPDATE_FAVORITE'
};
