export default {
  LOAD_USER: 'LOAD_USER',
  UPDATE_USER: 'UPDATE_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  ERROR_GENERIC: 'ERROR_GENERIC',
  LOGIN_ERROR: 'LOGIN_ERROR',
  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION'
};
