export default {
  LOAD_USERS: 'LOAD_USERS',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGIN_ERROR: 'AUTH_LOGIN_ERROR',
  ERROR_GENERIC: 'ERROR_GENERIC',
  CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION'
};
